name: Publish Package to npmjs
on: push
#  release:
#    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: fregante/setup-git-user@v1
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        name: Publish Package to npmjs
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn publish --preminor --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

